name: healthCheckPeriodic
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
     - cron:  '0 1 * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
 
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://pokemonindexfree.herokuapp.com/health
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 11